In [5]:
import tensorflow as tf

# 배달시간은 거리에 비례한다는 가정하에 간단하게 수식을 만들어 보자.
# 거리에 가중치를 곱하고 bias(편향, y좌표 위치)를 더한 식이다.
# 가중치의 변화는 그래프의 기울기 변화를 뜻하며 편향은 y좌표의 위치를 의미한다.
# 배달 시간 = 거리 * w + b
# 33분 = 850m * w + b

label = 33
distance = 850

# w와 b는 변수로 사용할 것이므로 tf.Variable로 지정
w = tf.Variable(0.)
b = tf.Variable(0.)

# 변수만 출력할 경우 여러 정보들을 볼 수 있음.
print(w)
# 데이터값, 수치만 출력할 경우 numpy 함수를 이용할 수 있음.
print(w.numpy())


<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>
0.0


In [8]:
# 손실함수는 예측값과 실제값의 차이를 줄여 알고리즘의 성능을 향상시킬때 사용하는 함수이다.
def loss_func():
  # 예측값을 얻기 위한 수식
  pred = distance * w + b

  # 실제값과 예측값의 차액이 음수가 될 수 있음으로 square함수 처리
  return tf.square(label - pred)

In [14]:
# 최적화 함수 중 평균적으로 성능이 좋은 Adam 함수 사용
# learning_rate는 0.1을 지정했으며, 0.01, 0.001 등을 사용할 수 있다.
opt = tf.keras.optimizers.Adam(learning_rate=0.1)

for i in range(1000):
  # 손실함수가 최소값을 갖기 위한 w, b 구하기
  opt.minimize(loss_func, var_list=[w, b])
  #print(w.numpy(), b.numpy())

In [15]:
distance * w + b

<tf.Tensor: shape=(), dtype=float32, numpy=32.999996>

#Quiz 
> 위의 코드를 이용하여, 손실함수가 최소값을 유지할 떄의 최소 반복횟수를 구하시오

In [ ]:
opt = tf.keras.optimizers.Adam(learning_rate=0.1)

rec_w = -100
rec_b = -100
for i in range(1000):
  opt.minimize(loss_func, var_list=[w, b])
  print( rec_w, w.numpy(),  rec_b, b.numpy())
  if (rec_w == w.numpy()) and (rec_b == b.numpy()):
    break
  else:
    rec_w = w.numpy()
    rec_b = b.numpy()




In [37]:
print(i)
distance * w + b

303


<tf.Tensor: shape=(), dtype=float32, numpy=32.999992>

# Quiz 강사님코드

In [40]:
opt = tf.keras.optimizers.Adam(learning_rate=0.1)

w_back = tf.Variable(0.)
b_back = tf.Variable(0.)

cnt = tf.Variable(0.)

while (True):
  opt.minimize(loss_func, var_list=[w, b])
  print(w.numpy(), b.numpy())

  if (w.numpy() == w_back.numpy()) and (b.numpy() == b_back.numpy()):
    break
 
  # w_back = w
  # 참조가 같아져서 항상 같은 값을 나타내게 됨

  w_back = tf.Variable(w.numpy())
  b_back = tf.Variable(b.numpy())

  cnt.assign_add(1)

-0.061179865 -0.059226524
0.013233561 0.015186902
0.084786355 0.08673972
0.114617825 0.11657119
0.10510945 0.10706282
0.07483876 0.07679212
0.03737142 0.03932478
0.004791308 0.0067446716
-0.013008431 -0.011055063
-0.013094324 -0.011140953
0.0011363355 0.0030897092
0.02378204 0.025735417
0.048156448 0.050109833
0.06761862 0.06957202
0.07729146 0.07924486
0.0757165 0.0776699
0.06468999 0.06664339
0.048018944 0.049972344
0.030456863 0.032410264
0.016707223 0.018660624
0.010157699 0.0121111
0.011886273 0.013839675
0.020624937 0.022578342
0.033432804 0.035386212
0.046549395 0.048502803
0.056349196 0.058302604
0.060363874 0.062317286
0.057969216 0.059922628
0.050394557 0.052347966
0.040199425 0.04215283
0.030501107 0.03245451
0.024083387 0.026036788
0.022572549 0.02452595
0.026006365 0.027959766
0.03295206 0.03490546
0.04103872 0.042992126
0.047707964 0.049661368
0.051007356 0.05296076
0.050180655 0.05213406
0.04582879 0.047782194
0.03962063 0.041574035
0.033699248 0.03565265
0.029968426 0.0

In [42]:
print(cnt.numpy())
distance * w + b

308.0


<tf.Tensor: shape=(), dtype=float32, numpy=32.999996>