현재까지 본 데이터넷
1. iris -> (수치형 변수1, 수치형 변수2, 수치형 변수3, 수치형 변수4 -> 품종)
2. german credit ->(수치형 변수1, 명목 변수, .....-> 신용도)
3. wine quality -> (수치형 변수1, 수치형 변수2, .....-> 와인의 품질 등급 1~9)
예측하는 곳에서 많이씀

wine quality data셋을 사용하기위해 https://archive.ics.uci.edu/ml/datasets/wine+quality여기서 다운로드

winequality-red.csv의 링크를 복사

In [28]:
import numpy as np
import pandas as pd

In [29]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"

redwine = np.loadtxt(url, delimiter=";", skiprows=1)

In [30]:
redwine

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [31]:
df = pd.read_csv(url, delimiter=";")
df.shape

(1599, 12)

In [32]:
df.head(10)

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5
5            7.4              0.66         0.00  ...       0.56      9.4        5
6            7.9              0.60         0.06  ...       0.46      9.4        5
7            7.3              0.65         0.00  ...       0.47     10.0        7
8            7.8              0.58         0.02  ...       0.57      9.5        7
9            7.5              0.50         0.36  ...       0.80     10.5        5

[10 rows x 12 columns]

In [33]:
redwine.mean()

7.926036165311652

In [34]:
redwine.mean(axis=0) #numpy에서는 axis는 행에대한 것이다?


array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311,  5.63602251])

In [35]:
redwine[:,0].mean()

8.31963727329581

In [36]:
redwine[:,0].max(axis=0)

15.9

In [37]:
redwine[:,0].min(axis=0)

4.6

In [38]:
#redwine[:,0].argmax

###**(실습)**

In [69]:
red_url = "winequality-red.csv"
white_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv"

red_df = pd.read_csv(red_url, delimiter=";")
red_df.shape

(1599, 12)

In [70]:
white_df = pd.read_csv(white_url, delimiter=";")
white_df.shape

(4898, 12)

In [71]:
white_df.values

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]])

In [72]:
red_df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [73]:
red_df.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [74]:
white_df.tail()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
4893            6.2              0.21         0.29  ...       0.50     11.2        6
4894            6.6              0.32         0.36  ...       0.46      9.6        5
4895            6.5              0.24         0.19  ...       0.46      9.4        6
4896            5.5              0.29         0.30  ...       0.38     12.8        7
4897            6.0              0.21         0.38  ...       0.32     11.8        6

[5 rows x 12 columns]

** red_df에서 pH가 가장 큰 숫자 5개를 추출하세요**

In [75]:
red_df.sort_values(by="pH", ascending=False).head(5)

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
1316            5.4              0.74         0.00  ...       0.59     12.5        6
1321            5.0              0.74         0.00  ...       0.59     12.5        6
695             5.1              0.47         0.02  ...       0.62     12.8        6
45              4.6              0.52         0.15  ...       0.56     13.1        4
95              4.7              0.60         0.17  ...       0.60     12.9        6

[5 rows x 12 columns]

In [76]:
red_df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

**pH, alcohol, density, quality로 구성된 new_red를 만드세요

In [77]:
new_red = red_df[["pH", "alcohol", "density","quality"]]
new_red

pH  alcohol  density  quality
0     3.51      9.4  0.99780        5
1     3.20      9.8  0.99680        5
2     3.26      9.8  0.99700        5
3     3.16      9.8  0.99800        6
4     3.51      9.4  0.99780        5
...    ...      ...      ...      ...
1594  3.45     10.5  0.99490        5
1595  3.52     11.2  0.99512        6
1596  3.42     11.0  0.99574        6
1597  3.57     10.2  0.99547        5
1598  3.39     11.0  0.99549        6

[1599 rows x 4 columns]

In [81]:
new_red.sort_values("quality", ascending=False).head(10)


pH  alcohol  density  quality
495   3.15     11.0  0.99720        8
1403  3.23     10.0  0.99600        8
390   3.56     12.9  0.99240        8
1061  3.21     12.5  0.99462        8
1202  3.35     11.7  0.99516        8
828   3.46     12.7  0.99417        8
481   3.15     11.7  0.99640        8
455   3.22     13.4  0.99880        8
1449  3.23     11.3  0.99472        8
440   2.88      9.8  0.99870        8

In [83]:
new_red.sort_values("quality", ascending=True).head(10)

pH  alcohol  density  quality
1478  3.40    10.20  0.99808        3
832   3.38     9.90  0.99832        3
899   3.48    11.00  0.99892        3
1374  3.32     9.80  0.99471        3
459   3.25     9.00  1.00080        3
517   3.16     8.40  0.99940        3
1469  3.31     9.70  0.99705        3
690   3.63    10.70  0.99660        3
1505  3.55     9.95  0.99600        3
1299  3.50    10.90  0.99476        3

In [85]:
red_df.loc[0:10, "fixed acidity": "alcohol"]

fixed acidity  volatile acidity  citric acid  ...    pH  sulphates  alcohol
0             7.4              0.70         0.00  ...  3.51       0.56      9.4
1             7.8              0.88         0.00  ...  3.20       0.68      9.8
2             7.8              0.76         0.04  ...  3.26       0.65      9.8
3            11.2              0.28         0.56  ...  3.16       0.58      9.8
4             7.4              0.70         0.00  ...  3.51       0.56      9.4
5             7.4              0.66         0.00  ...  3.51       0.56      9.4
6             7.9              0.60         0.06  ...  3.30       0.46      9.4
7             7.3              0.65         0.00  ...  3.39       0.47     10.0
8             7.8              0.58         0.02  ...  3.36       0.57      9.5
9             7.5              0.50         0.36  ...  3.35       0.80     10.5
10            6.7              0.58         0.08  ...  3.28       0.54      9.2

[11 rows x 11 columns]

In [89]:
red_df.iloc[0:10, 0:-1]

fixed acidity  volatile acidity  citric acid  ...    pH  sulphates  alcohol
0            7.4              0.70         0.00  ...  3.51       0.56      9.4
1            7.8              0.88         0.00  ...  3.20       0.68      9.8
2            7.8              0.76         0.04  ...  3.26       0.65      9.8
3           11.2              0.28         0.56  ...  3.16       0.58      9.8
4            7.4              0.70         0.00  ...  3.51       0.56      9.4
5            7.4              0.66         0.00  ...  3.51       0.56      9.4
6            7.9              0.60         0.06  ...  3.30       0.46      9.4
7            7.3              0.65         0.00  ...  3.39       0.47     10.0
8            7.8              0.58         0.02  ...  3.36       0.57      9.5
9            7.5              0.50         0.36  ...  3.35       0.80     10.5

[10 rows x 11 columns]

In [90]:
red_df.loc[1:2, ["volatile acidity", "citric acid"]]

volatile acidity  citric acid
1              0.88         0.00
2              0.76         0.04

In [91]:
red_df.iloc[1:3, 1:3]

volatile acidity  citric acid
1              0.88         0.00
2              0.76         0.04

In [100]:
red_df[(red_df.alcohol > 10)]

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
9               7.5             0.500         0.36  ...       0.80     10.5        5
11              7.5             0.500         0.36  ...       0.80     10.5        5
16              8.5             0.280         0.56  ...       0.75     10.5        7
30              6.7             0.675         0.07  ...       0.54     10.1        5
31              6.9             0.685         0.00  ...       0.57     10.6        6
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[852 rows x 12 columns]

**red_df에서 pH값이 6.0보다 크고 7.0보다 작은 데이터는?

In [119]:
red_df[(red_df["pH"]>3.5) & (red_df["pH"] <4.0)].sort_values(by="pH")

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
199             6.9             1.090         0.06  ...       0.43     11.4        4
302             8.3             0.705         0.12  ...       0.72     10.0        5
865             7.2             0.635         0.07  ...       0.54      9.7        5
864             7.2             0.620         0.06  ...       0.54      9.5        5
...             ...               ...          ...  ...        ...      ...      ...
1111            5.4             0.420         0.27  ...       0.64     12.3        7
1300            5.2             0.645         0.00  ...       0.61     12.5        6
95              4.7             0.600         0.17  ...       0.60     12.9        6
45              4.6             0.520         0.15  ...       0.56     13.1        4
695             5.1             0.470         0.02  ...       0.62     12.8        6

[166 rows x 12 columns]