In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [3]:
type(arr)

numpy.ndarray

In [4]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((3, 4, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [6]:
np.empty((4, 4))

array([[4.64307647e-310, 1.03977794e-312, 1.01855798e-312,
        9.54898106e-313],
       [1.10343781e-312, 1.01855798e-312, 1.23075756e-312,
        1.16709769e-312],
       [1.08221785e-312, 9.76118064e-313, 1.20953760e-312,
        1.06099790e-312],
       [1.01855798e-312, 4.44659081e-322, 0.00000000e+000,
        0.00000000e+000]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [9]:
arr= np.array([[1, 2, 3],[4, 5 ,6]])

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr.shape

(2, 3)

In [12]:
arr.ndim

2

In [13]:
arr.dtype

dtype('int64')

In [14]:
arr_int = np.array([1,2,3,4])
arr_int

array([1, 2, 3, 4])

In [15]:
arr_int.astype(np.float64).dtype

dtype('float64')

In [16]:
arr_str = np.array(["1", "2","3"])
arr_str

array(['1', '2', '3'], dtype='<U1')

In [17]:
arr_str.dtype

dtype('<U1')

In [18]:
arr_str.astype(np.int64).dtype  #문자가 숫자기때문에 되지만 만약  'a'와같은 문자라면 에러가 나온다.

dtype('int64')

###**행렬연산**

In [19]:
arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[5, 6],[7, 8]])

print(arr1 + arr2)
np.add(arr1, arr2)

[[ 6  8]
 [10 12]]


array([[ 6,  8],
       [10, 12]])

In [20]:
print(arr1*arr2)
np.multiply(arr1, arr2)

[[ 5 12]
 [21 32]]


array([[ 5, 12],
       [21, 32]])

In [21]:
#행렬 곱  행렬곱에서 
#B의 열의 수가 A의 행의 수와 맞아야한다.
#A(3, 5) => B(5, 8)
print(arr1.dot(arr2))

np.dot(arr1, arr2)


[[19 22]
 [43 50]]


array([[19, 22],
       [43, 50]])

###**ndarray배열 슬라이싱하기**

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr[0][0]

1

In [24]:
arr[2][2]

9

In [25]:
arr[:2, 1:3]

array([[2, 3],
       [5, 6]])

In [30]:
arr[[0, 1, 2],[2, 1, 0]]

array([3, 5, 7])

In [33]:
#arr[조건 슬라이싱]
arr>3  #조건에 대한 boolean

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [34]:
arr[arr>3]    #조건에 맞는 원소가져오기

array([4, 5, 6, 7, 8, 9])