In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
np.arange(15)   #일반 ragne와 같다.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
a = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
a = np.arange(15).reshape(3, -1)  #행 수에 맞게 열의 수를 맞춰준다.
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
np.arange(16).reshape(-1, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
a = np.arange(24).reshape(2, 3, -1)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
b = np.arange(36).reshape(2, 3, 2, 3)
b

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]]])

In [19]:
a.shape

(2, 3, 4)

In [20]:
b.shape

(2, 3, 2, 3)

In [24]:
a.itemsize #배열 각 원소의 bite사이즈

8

In [26]:
a.size #전체 원소의 수

24

In [27]:
b.size

36

In [29]:
np.linspace(0, 2, 9) #간격을 알아서 조정함

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
np.linspace(0, 2*3.14, 100)

array([0.        , 0.06343434, 0.12686869, 0.19030303, 0.25373737,
       0.31717172, 0.38060606, 0.4440404 , 0.50747475, 0.57090909,
       0.63434343, 0.69777778, 0.76121212, 0.82464646, 0.88808081,
       0.95151515, 1.01494949, 1.07838384, 1.14181818, 1.20525253,
       1.26868687, 1.33212121, 1.39555556, 1.4589899 , 1.52242424,
       1.58585859, 1.64929293, 1.71272727, 1.77616162, 1.83959596,
       1.9030303 , 1.96646465, 2.02989899, 2.09333333, 2.15676768,
       2.22020202, 2.28363636, 2.34707071, 2.41050505, 2.47393939,
       2.53737374, 2.60080808, 2.66424242, 2.72767677, 2.79111111,
       2.85454545, 2.9179798 , 2.98141414, 3.04484848, 3.10828283,
       3.17171717, 3.23515152, 3.29858586, 3.3620202 , 3.42545455,
       3.48888889, 3.55232323, 3.61575758, 3.67919192, 3.74262626,
       3.80606061, 3.86949495, 3.93292929, 3.99636364, 4.05979798,
       4.12323232, 4.18666667, 4.25010101, 4.31353535, 4.3769697 ,
       4.44040404, 4.50383838, 4.56727273, 4.63070707, 4.69414

In [33]:
np.arange(10000).reshape(100, 100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [35]:
def f(x,y):   #겁나 헷갈리는 펑션이네, f를 실행하는데 5행4열 행열을 f에 넣어줌
  print("x = ", x)
  print("y = ", y)
  return 10*x+y
np.fromfunction(f, (5, 4), dtype=int)

x =  [[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
y =  [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [37]:
b

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]]])

In [42]:
a = list(b.flat)  #행열을 1줄로 쭉 펴주는것
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]


In [43]:
np.argmax(a) #a 행렬에서 가장 큰 수가 있는 index를 리턴해준다.

35

In [44]:
a

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35]

SyntaxError: ignored

###**Indexing, Slicing and iterating**

In [46]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [47]:
a[2]

8

In [48]:
a[2:5]

array([ 8, 27, 64])

In [50]:
a[:6:2] = 1000 #0부터 2칸씩 건너뛰며, 6까지  1000으로 바꿈
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [52]:
a[::-1]  #역방향으로 

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [53]:
for i in a:
  print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [58]:
a = np.arange(0, 20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [59]:
a.reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [62]:
a.resize(2, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

###**slicing**

In [64]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
i = np.array([0, 2])
j = np.array([1, 2])